steps:
  - name: 'gcr.io/cloud-builders/npm'
    id: 'installing and executing Make'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install make
        make hello
        make test

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'stopping if fail'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        make stop BUILD_ID=$BUILD_ID
timeout: 660s
