steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Hello world"
  - name: 'gcr.io/cloud-builders/npm'
    args:
      - '-c'
      - |
        npm whoami
  - name: 'gcr.io/cloud-builders/npm'
    args:
      - '-c'
      - |
        npm run test
timeout: 660s
