steps:
  - name: 'gcr.io/cloud-builders/npm'
    id: 'installing and executing Make'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install make
        make hello
        make test

timeout: 660s
